[package]
name = "update-bindings"
publish = false

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
download-cef.workspace = true

bindgen.workspace = true
clap.workspace = true
convert_case.workspace = true
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true
thiserror.workspace = true
